# latest doconce, with scipy
# conda env create -f doconce_doconce_latest.yml
# or, to start from scratch,
# conda env create -f doconce_doconce_latest.yml --force
# install doconce via
# conda activate doconce_doconce_latest
# cd /Users/alexajo/github/doconce_doconce/
# git pull
# python setup.py install
# also add publish via
# pip install publish-doconce

name: doconce_doconce_latest
channels:
  - defaults
dependencies:
  - notebook
  - pip
  - python=3.6
  - pandas
  - matplotlib
  - scipy
